### ISSUE TITLE
Image URL without protocol

### ISSUE THREAD

**Issue by Webmasterei** [dbashyal/Magento-resize-category-images#20]
Thank you for the great plugin. Very simple and easy to use.

In my local installation the url ist //127.0.0.1/pathToImagte instead of http://127.0.0.1/andSoOn

Is this  a wrong setup?

**Comment by mkutyba** [comment]
It is intended behaviour, but I don't know the reason.
I removed it from here https://github.com/dbashyal/Magento-resize-category-images/blob/master/app/code/community/Technooze/Timage/Helper/Data.php#L69
