### ISSUE TITLE
Get width and height when resize and keepAspectRatio to true

### ISSUE THREAD

**Issue by dimitrilongo** [dbashyal/Magento-resize-category-images#31]
how can i retrieve new width and height when using `keepAspectRatio`

```<img src="<?php echo $this->helper('timage')->init($_MyCategory->getThumbnailUrl())->keepFrame(false)->keepAspectRatio(true)->resize(120, 25) ?>" alt="<?php echo $this->escapeHtml($_MyCategory->getName()) ?>" />```

I'd like to add `width` and `height` attribute to my `ìmg` tag

**Comment by dbashyal** [comment]
try:

`Mage::helper('timage')
            ->init(Mage::getBaseUrl('media') . 'catalog/product' . $image)
            ->setWidth(120)
            ->setHeight(25)
            //->keepFilename(true)
            //->keepAspectRatio(true)
            //->setDeveloperMode(true)
            ->centerCrop()
            ->resize();`
